"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """$directory$character"""
right_format = """$all"""

[directory]
truncation_length = 1
style = 'bold white'

[character] 
success_symbol = '[➜](#c10000) '
error_symbol = '[✗](#c0c0c0) '

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
